apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
  namespace: example-namespace
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /example-path
    server: efs.example.com